import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BookOpen, Headphones, LineChart, Mic2 } from "lucide-react";

const HomePage: React.FC = () => <>
  <section className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:py-24">
    <div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-700">TECHNOLOGY-GUIDED TARANNUM TRAINING</span><h1 className="mt-6 text-4xl font-bold leading-tight sm:text-5xl">Listen, follow and improve your recitation through a structured process.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Tarannum.ai supports reference-guided practice, melodic visualisation and self-recording. Tajwid and qualified teacher guidance remain essential.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/training" className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 font-semibold text-white">Start Training <ArrowRight size={18}/></Link><Link to="/demo" className="rounded-xl border border-slate-300 bg-white px-6 py-3 text-center font-semibold">View Demo</Link></div></div>
    <div className="grid grid-cols-2 gap-4 rounded-3xl bg-slate-950 p-6 text-white"><div className="rounded-2xl bg-white/10 p-5"><Headphones className="text-emerald-400"/><h2 className="mt-8 font-bold">Listen</h2><p className="mt-2 text-sm text-slate-300">Understand the reference.</p></div><div className="rounded-2xl bg-white/10 p-5"><LineChart className="text-blue-400"/><h2 className="mt-8 font-bold">Practise</h2><p className="mt-2 text-sm text-slate-300">Observe the melodic contour.</p></div><div className="rounded-2xl bg-white/10 p-5"><Mic2 className="text-amber-400"/><h2 className="mt-8 font-bold">Record</h2><p className="mt-2 text-sm text-slate-300">Review your recitation.</p></div><div className="rounded-2xl bg-white/10 p-5"><BookOpen className="text-violet-400"/><h2 className="mt-8 font-bold">Improve</h2><p className="mt-2 text-sm text-slate-300">Continue with teacher guidance.</p></div></div>
  </section>
  <section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><h2 className="text-3xl font-bold">A clear, focused workflow</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[["01","Select a session","Choose a Qari and reference recitation."],["02","Practise","Listen and follow the melodic contour at your own pace."],["03","Record when ready","Complete recording and assessment in the dedicated workspace."]].map(([n,h,p])=><div key={n} className="rounded-2xl border border-slate-200 p-6"><span className="text-sm font-bold text-emerald-600">{n}</span><h3 className="mt-4 text-xl font-bold">{h}</h3><p className="mt-2 text-slate-600">{p}</p></div>)}</div></div></section>
</>;
export default HomePage;
