import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BookOpen, Headphones, LineChart, Mic2 } from "lucide-react";
import { useI18n } from "../../i18n";

const copy = {
  en: { eyebrow:"TECHNOLOGY-GUIDED TARANNUM TRAINING", title:"Listen, follow and improve your recitation through a structured process.", intro:"Tarannum.ai supports reference-guided practice, melodic visualisation and self-recording. Tajwid and qualified teacher guidance remain essential.", start:"Start Training", demo:"View Demo", activities:[["Listen","Understand the reference."],["Practise","Observe the melodic contour."],["Record","Review your recitation."],["Improve","Continue with teacher guidance."]], workflow:"A clear, focused workflow", steps:[["01","Select a session","Choose a Qari and reference recitation."],["02","Practise","Listen and follow the melodic contour at your own pace."],["03","Record when ready","Complete recording and assessment in the dedicated workspace."]] },
  ms: { eyebrow:"LATIHAN TARANNUM BERPANDUKAN TEKNOLOGI", title:"Dengar, ikuti dan tingkatkan bacaan anda melalui proses yang tersusun.", intro:"Tarannum.ai menyokong latihan berpandukan bacaan rujukan, visualisasi melodi dan rakaman kendiri. Tajwid dan bimbingan guru berkelayakan kekal penting.", start:"Mulakan Latihan", demo:"Lihat Demo", activities:[["Dengar","Fahami bacaan rujukan."],["Berlatih","Perhatikan kontur melodi."],["Rakam","Semak bacaan anda."],["Tingkatkan","Teruskan dengan bimbingan guru."]], workflow:"Aliran kerja yang jelas dan berfokus", steps:[["01","Pilih sesi","Pilih Qari dan bacaan rujukan."],["02","Berlatih","Dengar dan ikuti kontur melodi mengikut keselesaan anda."],["03","Rakam apabila bersedia","Lengkapkan rakaman dan penilaian dalam ruang kerja khusus."]] },
} as const;

const HomePage: React.FC = () => { const { language }=useI18n(); const c=copy[language]; const icons=[Headphones,LineChart,Mic2,BookOpen]; const colors=["text-emerald-400","text-blue-400","text-amber-400","text-violet-400"]; return <>
  <section className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:py-24">
    <div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-700">{c.eyebrow}</span><h1 className="mt-6 text-4xl font-bold leading-tight sm:text-5xl">{c.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{c.intro}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/training" className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 font-semibold text-white">{c.start} <ArrowRight size={18}/></Link><Link to="/demo" className="rounded-xl border border-slate-300 bg-white px-6 py-3 text-center font-semibold">{c.demo}</Link></div></div>
    <div className="grid grid-cols-2 gap-4 rounded-3xl bg-slate-950 p-6 text-white">{c.activities.map(([h,p],index)=>{const Icon=icons[index]; return <div key={h} className="rounded-2xl bg-white/10 p-5"><Icon className={colors[index]}/><h2 className="mt-8 font-bold">{h}</h2><p className="mt-2 text-sm text-slate-300">{p}</p></div>;})}</div>
  </section>
  <section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><h2 className="text-3xl font-bold">{c.workflow}</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{c.steps.map(([n,h,p])=><div key={n} className="rounded-2xl border border-slate-200 p-6"><span className="text-sm font-bold text-emerald-600">{n}</span><h3 className="mt-4 text-xl font-bold">{h}</h3><p className="mt-2 text-slate-600">{p}</p></div>)}</div></div></section>
</>; };
export default HomePage;
