[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
startCommand = "celery -A task_queue.celery_app worker --loglevel=INFO --pool=threads --concurrency=2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
